# Generated by Django 6.0.6 on 2026-07-22 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylogdetails',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='buylogdetails',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BuyLogDetailField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. Email, Password, API Key, PIN', max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('is_sensitive', models.BooleanField(default=True, help_text='If true, shown as a copy-to-clipboard credential on the receipt.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_fields', to='Business.buylogdetails')),
            ],
            options={
                'verbose_name': 'Credential Field',
                'ordering': ['sort_order'],
            },
        ),
    ]
