# Generated by Django 6.0.6 on 2026-07-13 05:11

import Business.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TransEdge Global', max_length=100)),
                ('tagline', models.CharField(default='Precision Logistics, Global Reach', max_length=255)),
                ('hero_subtitle', models.TextField(default='Navigating complexity with precision. End-to-end supply chain solutions.')),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email_support', models.EmailField(blank=True, max_length=254)),
                ('email_info', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code e.g. 2348012345678', max_length=20)),
                ('hero_image_url', models.URLField(blank=True, help_text='URL of the hero background image')),
                ('stat_deliveries', models.CharField(default='15k+', max_length=20)),
                ('stat_satisfaction', models.CharField(default='98%', max_length=20)),
                ('stat_support', models.CharField(default='24/7', max_length=20)),
                ('copyright_text', models.CharField(default='© 2024 TransEdge Global. All rights reserved.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. COO, GlobalTech Solutions', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('avatar_url', models.URLField(blank=True, help_text='Use URL if no file upload')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1–5 stars')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pointspricing',
            name='invoice_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Flat fee added to every invoice created from a shipment.', max_digits=14),
        ),
        migrations.AddField(
            model_name='pointspricing',
            name='points_per_invoice',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pointspricing',
            name='points_per_support_link',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shipment',
            name='support_link_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='support_link_label',
            field=models.CharField(blank=True, default='Chat with Support', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='support_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='subadminprofile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='ClientEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declared_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid Out'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='Business.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('tracking_created', 'Tracking ID Created'), ('status_update', 'Status Update'), ('delivery_alert', 'Delivery Alert'), ('payment_reminder', 'Payment Reminder'), ('payment_confirmed', 'Payment Confirmed'), ('custom', 'Custom Message')], max_length=25)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='Business.shipment')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(default=Business.models.generate_invoice_number, editable=False, max_length=20, unique=True)),
                ('bill_to_name', models.CharField(blank=True, max_length=255)),
                ('bill_to_email', models.EmailField(blank=True, max_length=254)),
                ('bill_to_address', models.TextField(blank=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, default='Payment due within 7 days of invoice date.')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Business.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Business.invoice')),
            ],
        ),
    ]
