# Generated by Django 6.0.6 on 2026-07-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_copy_buylog_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buylogdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buylogdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='buylogdetails',
            name='recovery_email',
        ),
        migrations.RemoveField(
            model_name='buylogdetails',
            name='two_factor_code',
        ),
    ]
