# Generated by Django 6.0.6 on 2026-07-13 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_account_foreignnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('paystack_reference', models.CharField(max_length=200, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='Business.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
