# Generated by Django 6.0.6 on 2026-07-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_remove_buylogdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylogs',
            name='credential_format',
            field=models.CharField(blank=True, default='Email,Password', help_text="Comma-separated field labels, in the order they'll appear when bulk-pasting stock. E.g. 'Email,Password' or 'Username,PIN,Recovery Code'.", max_length=255),
        ),
    ]
