# Generated by Django 6.0.6 on 2026-07-15 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0004_walletdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointspricing',
            name='points_per_site_customization',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_public', models.BooleanField(default=False, help_text='If True and recipient is blank, all sub-admins see this.')),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Optional action link shown as a button (e.g. /sub-admin/buy-points/).')),
                ('link_label', models.CharField(blank=True, default='View', max_length=80)),
                ('is_read', models.BooleanField(default=False, help_text='For private notifications only. Public ones use NotificationRead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave blank to send to all sub-admins (public broadcast).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubAdminSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Upload a logo image.', null=True, upload_to='site_logos/')),
                ('logo_url', models.URLField(blank=True, help_text="Use a URL if you don't want to upload a file.")),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, help_text='Hex color e.g. #38bdf8', max_length=20)),
                ('hero_title', models.CharField(blank=True, default='', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('hero_image_url', models.URLField(blank=True)),
                ('about_text', models.TextField(blank=True, help_text='About section shown on the public landing page.')),
                ('stat_deliveries', models.CharField(blank=True, default='', max_length=20)),
                ('stat_satisfaction', models.CharField(blank=True, default='', max_length=20)),
                ('stat_support', models.CharField(blank=True, default='', max_length=20)),
                ('phone_primary', models.CharField(blank=True, default='', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='', max_length=30)),
                ('email_support', models.EmailField(blank=True, default='', max_length=254)),
                ('email_info', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('google_maps_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, no + e.g. 2348012345678', max_length=20)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_admin', models.OneToOneField(blank=True, help_text='Null = global default (set by super-admin).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='Business.subadminprofile')),
            ],
            options={
                'verbose_name': 'Sub-Admin Site Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='Business.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
