# Generated by Django 6.0.6 on 2026-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_buylogs_credential_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('GHS', 'Ghanaian Cedi (₵)')], default='USD', max_length=5),
        ),
    ]
