# Generated by Django 6.0.6 on 2026-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_pointspricing_points_per_site_customization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='driver_chat_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_vehicle_info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
