# Generated by Django 6.0.6 on 2026-07-18 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_shipment_driver_chat_url_shipment_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('working_tools', 'Working Tools'), ('tiktok', 'TikTok')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='categories/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Product',
                'verbose_name_plural': 'Log Products',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BuyLogDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('recovery_email', models.CharField(blank=True, max_length=200)),
                ('two_factor_code', models.CharField(blank=True, max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_logs_added', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Business.buylogs')),
            ],
            options={
                'verbose_name': 'Log Stock Item',
                'verbose_name_plural': 'Log Stock Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Wallet the purchase was debited from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_purchases', to='Business.account')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_purchases', to=settings.AUTH_USER_MODEL)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='Business.buylogdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Business.buylogs')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
