# Generated by Django 6.0.6 on 2026-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0007_buylogs_buylogdetails_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard_adverts/')),
                ('cta_text', models.CharField(default='Learn More', max_length=40)),
                ('cta_url', models.URLField(blank=True)),
                ('background_start', models.CharField(default='#3B82F6', help_text='Gradient start hex color', max_length=20)),
                ('background_end', models.CharField(default='#1E3A8A', help_text='Gradient end hex color', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
