# Generated by Django 6.0.6 on 2026-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0007_tutorialcategory_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignnumber',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
