# Generated by Django 6.0.6 on 2026-07-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_dashboardadvert'),
    ]


    operations = [
    # 1. Create the Category table first
    migrations.CreateModel(
        name='Category',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=50, unique=True)),
            ('slug', models.SlugField(max_length=60, unique=True, blank=True)),
            ('icon', models.CharField(blank=True, help_text="Font Awesome class, e.g. 'fab fa-facebook'", max_length=60)),
            ('is_active', models.BooleanField(default=True)),
            ('order', models.PositiveIntegerField(default=0)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ],
        options={
            'verbose_name_plural': 'Categories',
            'ordering': ['order', 'name'],
        },
    ),

    # 2. Add a temporary nullable FK column
    migrations.AddField(
        model_name='buylogs',
        name='category_new',
        field=models.ForeignKey(
            'Business.Category',
            null=True,
            blank=True,
            on_delete=django.db.models.deletion.PROTECT,
            related_name='products',
        ),
    ),

    # 3. Data migration — clear the old string value (can't map 'facebook' to a real Category)
    migrations.RunSQL(
        sql="UPDATE Business_buylogs SET category_new_id = NULL",
        reverse_sql=migrations.RunSQL.noop,
    ),

    # 4. Remove the old string column
    migrations.RemoveField(
        model_name='buylogs',
        name='category',
    ),

    # 5. Rename the new column to 'category'
    migrations.RenameField(
        model_name='buylogs',
        old_name='category_new',
        new_name='category',
    ),
]
