# Generated by Django 6.0.6 on 2026-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_foreignnumber_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletdeposit',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='walletdeposit',
            name='provider_transaction_ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
