# Generated by Django 6.0.6 on 2026-07-28 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0009_walletdeposit_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('buy_logs', 'Buy Logs'), ('foreign_numbers', 'Foreign Numbers (SMS)'), ('shipments', 'Create Shipment'), ('wallet_deposit', 'Wallet Deposit'), ('buy_points', 'Buy Points'), ('tutorials', 'Tutorials'), ('all', 'Entire Platform')], max_length=30, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, help_text='Message shown to sub-admins when they hit the lock. Required while locked.', max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Lock',
                'ordering': ['service'],
            },
        ),
    ]
