# Generated by Django 6.0.6 on 2026-07-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_alter_buylogs_category_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(default='Join Group', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
