# Generated by Django 6.0.6 on 2026-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0011_dashboardannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_gallery/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
