# Generated by Django 6.0.6 on 2026-07-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0012_brandgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='subadmin_gallery/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Business.subadminprofile')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
