# Generated by Django 6.0.6 on 2026-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0013_subadmingalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='support_link_type',
            field=models.CharField(choices=[('link', 'Chat Link / URL'), ('email', 'Email Address')], default='link', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='support_link_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
